# Generated by Django 4.0.2 on 2022-04-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingPerson', '0003_alter_missingperson_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='birthDate',
            field=models.DateTimeField(null=True),
        ),
    ]
