# Generated by Django 4.0.2 on 2022-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingPerson', '0007_alter_missingperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(null=True, upload_to='missing-person'),
        ),
    ]
