# Generated by Django 4.0.2 on 2022-05-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingPerson', '0008_missingperson_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('FOUND', 'Found'), ('MISSING', 'Missing'), ('PENDING', 'Pending')], default='PENDING', max_length=7),
        ),
    ]
