# Generated by Django 4.0.2 on 2022-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingPerson', '0009_alter_missingperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
