# Generated by Django 4.0.2 on 2022-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingPerson', '0010_missingperson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
