# Generated by Django 4.0.2 on 2022-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid',
            field=models.CharField(default=78964653135, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
