# Generated by Django 4.0.2 on 2022-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null='True', upload_to='profile-photo'),
            preserve_default='True',
        ),
    ]
