# Generated by Django 4.0.2 on 2022-02-19 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal', models.CharField(max_length=1000)),
                ('victim', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('GD', 'GD'), ('CF', 'CASE FILE')], default='GD', max_length=2)),
                ('phone', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('P', 'Investigating'), ('P', 'Dismissed')], default='P', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
