# Generated by Django 4.0.2 on 2022-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeFile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='title',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
    ]
