# Generated by Django 4.0.2 on 2022-02-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeFile', '0004_alter_complain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('dismissed', 'Dismissed')], default='pending', max_length=255),
        ),
    ]
