# Generated by Django 4.0.2 on 2022-05-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wantedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('fathersName', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ARRESTED', 'Arrested'), ('WANTED', 'Wanted')], default='WANTED', max_length=10)),
                ('photo', models.ImageField(null=True, upload_to='wanted-person')),
                ('nid_birthid', models.CharField(max_length=255)),
            ],
        ),
    ]
